2-dice added
Josef-adilson27/js-advanced pull request #2
Opened 2024-10-07 15:52 UTC by Josef-adilson27

2024-10-09 08:23 UTC, Levitinn requested changes

2024-10-09 08:23 UTC, Levitinn commented on JS-advanced/2-dice.js
здесь тоже есть что переделать. 
Если acceptDices сделать объектом, то returnNumber займет две строки

2024-10-10 08:37 UTC, Josef-adilson27 commented on JS-advanced/2-dice.js
> +
получаем правильные кости и намеренно неправильные  для проверки

2024-10-14 19:12 UTC, Levitinn approved these changes

2024-10-22 22:04 UTC, merged