4-timer init
Josef-adilson27/js-advanced pull request #4
Opened 2024-10-15 15:29 UTC by Josef-adilson27

2024-10-22 19:29 UTC, Levitinn requested changes

2024-10-22 19:29 UTC, Levitinn commented on JS-advanced/timer/4-timer.js
давай попробуем сделать так, чтобы у тебя была всего лишь одна функция, которая будет содержать всю необходимую логику. 
т.е. вызвав одну функцию все будет работать как предполагалось. 
сейчас у тебя переменные, функция и сетИнтервал, что делает неудобным переиспользование этой функции.

2024-10-22 22:02 UTC, Josef-adilson27 commented on JS-advanced/timer/4-timer.js
а ну да логично

2024-10-23 19:48 UTC, Levitinn approved these changes

2024-10-23 22:07 UTC, merged